project_name: terminus-cli
builds:
  - id: linux_amd64
    env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    binary: terminus-cli
    main: ./cmd/main.go
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - exclude_graphdriver_devicemapper
      - exclude_graphdriver_btrfs
      - containers_image_openpgp
      - linux
    ldflags:
      - -w
      - -s
  # - id: linux_arm
  #   env:
  #     - GOOS=linux
  #     - GOARCH=arm
  #     - GOARM=7
  #   binary: terminus-cli
  #   main: ./cmd/main.go
  #   goarch:
  #     - arm
  #   goos:
  #     - linux
  #   goarm:
  #     - 7
  #   tags:
  #     - exclude_graphdriver_devicemapper
  #     - exclude_graphdriver_btrfs
  #     - containers_image_openpgp
  #   ldflags:
  #     - -w
  #     - -s
  # - id: darwin_amd64
  #   env:
  #     - CGO_ENABLED=0
  #     - GOOS=darwin
  #     - GOARCH=amd64
  #   binary: terminus-cli
  #   main: ./cmd/main.go
  #   goos:
  #     - darwin
  #   goarch:
  #     - amd64
  #   tags:
  #     - exclude_graphdriver_devicemapper
  #     - exclude_graphdriver_btrfs
  #     - containers_image_openpgp
  #     - darwin
  #     - amd64
  #   ldflags:
  #     - -w
  #     - -s
  # - id: darwin_arm64
  #   env:
  #     - CGO_ENABLED=0
  #     - GOOS=darwin
  #     - GOARCH=arm64
  #   binary: terminus-cli
  #   main: ./cmd/main.go
  #   goos:
  #     - darwin
  #   goarch:
  #     - arm64
  #   tags:
  #     - exclude_graphdriver_devicemapper
  #     - exclude_graphdriver_btrfs
  #     - containers_image_openpgp
  #     - darwin
  #     - arm64
  #   ldflags:
  #     - -w
  #     - -s
dist: ./output
archives:
  - id: terminus-cli
    name_template: "{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: linux
      amd64: amd64
      arm: arm64
    files:
      - none*
checksum:
  name_template: "checksums.txt"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: true
  draft: false
